---
- name: copyplaybook
  hosts: all
  tasks:
    - name: copy_file
      copy:
        src: /root/shell_script.sh
        dest: /root
    - name: shellscript
      shell: sh /root/shell_script.sh
      register: target_sh
    - debug:
        var: target_sh.stdout_lines
